---
- name: Create, Attach, and Mount Persistent Disk in GCP
  hosts: all
  gather_facts: no
  tasks:
    - name: Set GCP project
      command: gcloud config set project {{ project_id }}
      environment:
        GOOGLE_APPLICATION_CREDENTIALS: "{{ google_credentials_path }}"
      delegate_to: localhost

    - name: Create Persistent Disk in GCP
      command: >
        gcloud compute disks create {{ disk_name }}
        --size={{ disk_size }}
        --zone={{ zone }}
      environment:
        GOOGLE_APPLICATION_CREDENTIALS: "{{ google_credentials_path }}"
      delegate_to: localhost

    - name: Attach Persistent Disk to VM with the same device name as disk
      command: >
        gcloud compute instances attach-disk {{ vm_name }}
        --disk {{ disk_name }}
        --zone {{ zone }}
        --device-name {{ disk_name }}
      environment:
        GOOGLE_APPLICATION_CREDENTIALS: "{{ google_credentials_path }}"
      delegate_to: localhost

    - name: Find the device name associated with the disk
      command: >
        gcloud compute instances describe {{ vm_name }}
        --zone={{ zone }}
        --format="get(disks.deviceName)"
      register: disk_device_name
      environment:
        GOOGLE_APPLICATION_CREDENTIALS: "{{ google_credentials_path }}"
      delegate_to: localhost

    - name: Format the disk (if not already formatted)
      command: mkfs.ext4 /dev/disk/by-id/google-{{ disk_name }}
      when: disk_device_name.stdout != ""
      become: yes

    - name: Create custom mount point for the disk
      file:
        path: "{{ custom_mount_point }}"
        state: directory
      become: yes

   

    - name: Get the UUID of the disk
      command: blkid -s UUID -o value /dev/disk/by-id/google-{{  disk_name }}
      register: disk_uuid
      become: yes

    - name: Add entry to /etc/fstab for persistent mounting
      lineinfile:
        path: /etc/fstab
        line: "UUID={{ disk_uuid.stdout }} {{ custom_mount_point }} ext4 defaults 0 2"
        state: present
      become: yes
    
    - name: Mount all entries in /etc/fstab
      command: mount -a && systemctl daemon-reload
      become: yes