---
- name: Install and Restart Services
  hosts: all
  become: yes
  tasks:
    - name: Install selected packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
      notify: Restart Services

  handlers:
    - name: Restart Services
      service:
        name: "{{ item }}"
        state: restarted
      loop: "{{ services }}"
