---
- name: Install and Restart Services
  hosts: all
  become: yes
  tasks:
    - name: Install selected package
      apt:
        name: "{{ package }}"
        state: present
      notify: Restart Service

  handlers:
    - name: Restart Service
      service:
        name: "{{ service }}"
        state: restarted
